apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
      app: web
      version: "1.14"
  template:
    metadata:
      labels:
        app: web
        version: "1.14"
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
        ports:
          - containerPort: 80

