# mongo-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo
    # mongo의 Entrypoint를 아래의 command로 변경하여, Entrypoint의 스크립트의 /data/db의 권한변경 작업을 못 하도록 합니다.
    # mongoDB는 ip bind가 loopBack으로 되어 있어 원격에서 접속이 되지 않습니다. 원격에서 접속 가능하도록 bind_ip 를 추가하였습니다.
    command: 
      - "mongod"
      - "--bind_ip"
      - "0.0.0.0"
    ports:
      - containerPort: 27017
        protocol: TCP
    volumeMounts:
      - mountPath: /data/db
        name: dbdata
  volumes:
    - name: dbdata
      persistentVolumeClaim:
        claimName: mongodb-pvc