---
# nfs-pv1.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
spec:
  capacity:
    storage: 1Gi # PV의 크기는 1GiB 로 설정 하였습니다.
  volumeMode: Filesystem
  accessModes:   # PV의 AccessMode는 DB에서 사용할 수 있도록 RWO, RWX를 설정하였습니다.
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # DB(MongoDB)를 사용할 것이기 때문에 Retain으로 설정 합니다.
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/data-pv1    # NFS에서 설정한 디렉토리를 명시 합니다.
    server: node1